# SITE CONFIGURATION
title: Jinbo # your site title
author: jinbooooom # You :P
description: > # Meta description of Homepage
  Python/C/C++ developer, artificial intelligence enthusiast.
baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://jinbooooom.github.io//" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Jinbo
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/jinbooooom
    - https://jinbooooom.github.io/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jinboom@foxmail.com # email for form submission

twitter_username: jinbo # replace with your_twitter_username or comment to remove link from footer
github_username:  jinbooooom # replace with your_github_username or comment to remove link from footer
instagram_username: jinbo # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: jinbo # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
