# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://jinbooooom.github.io
date_format: "ordinal"
title: 随心
subtitle: "follow the heart"
description: "随心的个人博客"
keywords: 随心, Jinbo, jinbooooom, 闻故知新
timezone: China/Anhui
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jinbo
organization: 
organization_url: 
github_username: jinbooooom
location: Huanggang,China
email: jinboom@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#  -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: jinbooooom/jinbooooom.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: jinbooooom
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jinbooooom
    repo: blog-comments
    oauth: 
        client_id: 5964b7224a4c9887036b
        client_secret: 6302eab89a4f3a492364072bd999b209f014ce99
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jinbooooom
    repo: blog-comments
    clientID: 5964b7224a4c9887036b
    clientSecret: 6302eab89a4f3a492364072bd999b209f014ce99
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

theme: jekyll-theme-cayman